import os
from supabase import create_client
from dotenv import load_dotenv

load_dotenv()
url = os.environ.get("SUPABASE_URL")
key = os.environ.get("SUPABASE_KEY")
supabase = create_client(url, key)

# favoritesテーブルの作成をRPC経由で実行
sql = """
CREATE TABLE IF NOT EXISTS favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_symbol VARCHAR(10) REFERENCES companies(ticker_symbol) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(ticker_symbol)
);
"""

try:
    supabase.rpc("exec_sql", {"query": sql}).execute()
    print("✅ favoritesテーブルを作成しました！")
except Exception as e:
    print(f"RPC方式では作成できませんでした: {e}")
    print("\n代替方法: Supabaseダッシュボードの SQL Editor で以下のSQLを実行してください:")
    print(sql)
    print("※ダッシュボードが不安定な場合は、少し時間を置いてからリトライしてください。")
