-- ==========================================
-- 日本株投資先発掘アプリ データベース定義 (Supabase / PostgreSQL)
-- ==========================================

-- 1. companies (企業マスターテーブル)
CREATE TABLE companies (
    ticker_symbol VARCHAR(10) PRIMARY KEY,
    company_name VARCHAR(255) NOT NULL,
    market VARCHAR(50),
    sector_33 VARCHAR(100),
    status VARCHAR(20) DEFAULT 'ACTIVE', -- 'ACTIVE' or 'DELISTED'
    delisted_date DATE,
    fiscal_month SMALLINT,
    next_earnings_date DATE,
    dividend_yield DOUBLE PRECISION,     -- 予想配当利回り(%)
    extra_data JSONB DEFAULT '{}'::jsonb -- 自由拡張枠
);

-- 2. company_name_histories (社名変更履歴テーブル)
CREATE TABLE company_name_histories (
    history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_symbol VARCHAR(10) REFERENCES companies(ticker_symbol) ON DELETE CASCADE,
    old_company_name VARCHAR(255) NOT NULL,
    new_company_name VARCHAR(255) NOT NULL,
    effective_date DATE NOT NULL
);

-- 3. daily_stock_prices (日次株価テーブル)
CREATE TABLE daily_stock_prices (
    ticker_symbol VARCHAR(10) REFERENCES companies(ticker_symbol) ON DELETE CASCADE,
    trade_date DATE NOT NULL,
    open_price DOUBLE PRECISION,
    high_price DOUBLE PRECISION,
    low_price DOUBLE PRECISION,
    close_price DOUBLE PRECISION,
    adjusted_close DOUBLE PRECISION,     -- 株式分割対応用の調整後終値
    volume BIGINT,
    price_change DOUBLE PRECISION,       -- 前日比
    is_stop_high BOOLEAN DEFAULT FALSE,  -- ストップ高フラグ
    is_stop_low BOOLEAN DEFAULT FALSE,   -- ストップ安フラグ
    extra_data JSONB DEFAULT '{}'::jsonb,-- 自由拡張枠
    PRIMARY KEY (ticker_symbol, trade_date)
);

-- ★パフォーマンス対策インデックス★
-- Streamlit側で「直近の株価」や「本日のストップ高」を高速検索するために必須
CREATE INDEX idx_daily_stock_prices_date ON daily_stock_prices(trade_date DESC);
CREATE INDEX idx_daily_stock_prices_stop_high ON daily_stock_prices(is_stop_high) WHERE is_stop_high = TRUE;
CREATE INDEX idx_daily_stock_prices_stop_low ON daily_stock_prices(is_stop_low) WHERE is_stop_low = TRUE;

-- 4. shareholder_benefits (株主優待テーブル)
CREATE TABLE shareholder_benefits (
    benefit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_symbol VARCHAR(10) REFERENCES companies(ticker_symbol) ON DELETE CASCADE,
    record_month SMALLINT,               -- 権利確定月 (1〜12)
    min_shares INTEGER,                  -- 最低必要株数
    benefit_summary TEXT,                -- 優待内容要約
    is_active BOOLEAN DEFAULT TRUE,      -- 有効フラグ
    abolished_date DATE,                 -- 廃止日
    extra_data JSONB DEFAULT '{}'::jsonb
);

-- 5. margin_balances (信用取引残高テーブル)
CREATE TABLE margin_balances (
    ticker_symbol VARCHAR(10) REFERENCES companies(ticker_symbol) ON DELETE CASCADE,
    report_date DATE NOT NULL,           -- 基準日（金曜日）
    margin_buy_volume BIGINT,            -- 買い残
    margin_sell_volume BIGINT,           -- 売り残
    margin_ratio DOUBLE PRECISION,       -- 信用倍率
    PRIMARY KEY (ticker_symbol, report_date)
);

-- 最新の信用残高を高速に取得するためのインデックス
CREATE INDEX idx_margin_balances_date ON margin_balances(report_date DESC);
